image: alpine/latest
packages:
  - go
  # Required by codecov
  - bash
  - findutils
sources:
  - https://github.com/sebas05000/go-sasl
tasks:
  - build: |
      cd go-sasl
      go build -v ./...
  - test: |
      cd go-sasl
      go test -coverprofile=coverage.txt -covermode=atomic ./...
  - upload-coverage: |
      cd go-sasl
      export CODECOV_TOKEN=ab6ef672-9ccc-4b0b-87d0-952e7433dd95
      curl -s https://codecov.io/bash | bash
